STATE_CHOICES = [
    ("ss", "Select your state"),
    ("Andaman Nicobar", "Andaman Nicobar"),
    ("Andhra Pradesh", "Andhra Pradesh"),
    ("Arunachal Pradesh", "Arunachal Pradesh"),
    ("Assam", "Assam"),
    ("Bihar", "Bihar"),
    ("Chandigarh", "Chandigarh"),
    ("Chhattisgarh", "Chhattisgarh"),
    ("Dadra Nagar Haveli and Daman and Diu", "Dadra Nagar Haveli and Daman and Diu"),
    ("Delhi", "Delhi"),
    ("Goa", "Goa"),
    ("Gujarat", "Gujarat"),
    ("Haryana", "Haryana"),
    ("Himachal Pradesh", "Himachal Pradesh"),
    ("Jammu Kashmir", "Jammu Kashmir"),
    ("Jharkhand", "Jharkhand"),
    ("Karnataka", "Karnataka"),
    ("Kerala", "Kerala"),
    ("Ladakh", "Ladakh"),
    ("Lakshadweep", "Lakshadweep"),
    ("Madhya Pradesh", "Madhya Pradesh"),
    ("Maharashtra", "Maharashtra"),
    ("Manipur", "Manipur"),
    ("Meghalaya", "Meghalaya"),
    ("Mizoram", "Mizoram"),
    ("Nagaland", "Nagaland"),
    ("Odisha", "Odisha"),
    ("Puducherry", "Puducherry"),
    ("Punjab", "Punjab"),
    ("Rajasthan", "Rajasthan"),
    ("Sikkim", "Sikkim"),
    ("Tamil Nadu", "Tamil Nadu"),
    ("Telangana", "Telangana"),
    ("Tripura", "Tripura"),
    ("Uttar Pradesh", "Uttar Pradesh"),
    ("Uttarakhand", "Uttarakhand"),
    ("West Bengal", "West Bengal"),
]

DISTRICT_CHOICES = [
    ("", "Select your district"),
    (
        "Andaman Nicobar",
        (
            ("nicobar", "Nicobar"),
            ("north middle andaman", "North Middle Andaman"),
            ("south andaman", "South Andaman"),
        ),
    ),
    (
        "Andhra Pradesh",
        (
            ("alluri sitarama raju", "Alluri Sitarama Raju"),
            ("anakapalli", "Anakapalli"),
            ("anantapur", "Anantapur"),
            ("annamaya", "Annamaya"),
            ("bapatla", "Bapatla"),
            ("chittoor", "Chittoor"),
            ("east godavari", "East Godavari"),
            ("eluru", "Eluru"),
            ("guntur", "Guntur"),
            ("kadapa", "Kadapa"),
            ("kakinada ", "Kakinada "),
            ("konaseema", "Konaseema"),
            ("krishna", "Krishna"),
            ("kurnool", "Kurnool"),
            ("manyam", "Manyam"),
            ("n t rama rao", "N T Rama Rao"),
            ("nandyal", "Nandyal"),
            ("nellore", "Nellore"),
            ("palnadu", "Palnadu"),
            ("prakasam", "Prakasam"),
            ("sri balaji", "Sri Balaji"),
            ("sri satya sai", "Sri Satya Sai"),
            ("srikakulam", "Srikakulam"),
            ("visakhapatnam", "Visakhapatnam"),
            ("vizianagaram", "Vizianagaram"),
            ("west godavari", "West Godavari"),
        ),
    ),
    (
        "Arunachal Pradesh",
        (
            ("anjaw", "Anjaw"),
            ("changlang", "Changlang"),
            ("dibang valley", "Dibang Valley"),
            ("east kameng", "East Kameng"),
            ("east siang", "East Siang"),
            ("kamle", "Kamle"),
            ("kra daadi", "Kra Daadi"),
            ("kurung kumey", "Kurung Kumey"),
            ("lepa rada", "Lepa Rada"),
            ("lohit", "Lohit"),
            ("longding", "Longding"),
            ("lower dibang valley", "Lower Dibang Valley"),
            ("lower siang", "Lower Siang"),
            ("lower subansiri", "Lower Subansiri"),
            ("namsai", "Namsai"),
            ("pakke kessang", "Pakke Kessang"),
            ("papum pare", "Papum Pare"),
            ("shi yomi", "Shi Yomi"),
            ("siang", "Siang"),
            ("tawang", "Tawang"),
            ("tirap", "Tirap"),
            ("upper siang", "Upper Siang"),
            ("upper subansiri", "Upper Subansiri"),
            ("west kameng", "West Kameng"),
            ("west siang", "West Siang"),
        ),
    ),
    (
        "Assam",
        (
            ("bajali", "Bajali"),
            ("baksa", "Baksa"),
            ("barpeta", "Barpeta"),
            ("biswanath", "Biswanath"),
            ("bongaigaon", "Bongaigaon"),
            ("cachar", "Cachar"),
            ("charaideo", "Charaideo"),
            ("chirang", "Chirang"),
            ("darrang", "Darrang"),
            ("dhemaji", "Dhemaji"),
            ("dhubri", "Dhubri"),
            ("dibrugarh", "Dibrugarh"),
            ("dima hasao", "Dima Hasao"),
            ("goalpara", "Goalpara"),
            ("golaghat", "Golaghat"),
            ("hailakandi", "Hailakandi"),
            ("hojai", "Hojai"),
            ("jorhat", "Jorhat"),
            ("kamrup", "Kamrup"),
            ("kamrup metropolitan", "Kamrup Metropolitan"),
            ("karbi anglong", "Karbi Anglong"),
            ("karimganj", "Karimganj"),
            ("kokrajhar", "Kokrajhar"),
            ("lakhimpur", "Lakhimpur"),
            ("majuli", "Majuli"),
            ("morigaon", "Morigaon"),
            ("nagaon", "Nagaon"),
            ("nalbari", "Nalbari"),
            ("sivasagar", "Sivasagar"),
            ("sonitpur", "Sonitpur"),
            ("south salmara-mankachar", "South Salmara-Mankachar"),
            ("tinsukia", "Tinsukia"),
            ("udalguri", "Udalguri"),
            ("west karbi anglong", "West Karbi Anglong"),
        ),
    ),
    (
        "Bihar",
        (
            ("araria", "Araria"),
            ("arwal", "Arwal"),
            ("aurangabad", "Aurangabad"),
            ("banka", "Banka"),
            ("begusarai", "Begusarai"),
            ("bhagalpur", "Bhagalpur"),
            ("bhojpur", "Bhojpur"),
            ("buxar", "Buxar"),
            ("darbhanga", "Darbhanga"),
            ("east champaran", "East Champaran"),
            ("gaya", "Gaya"),
            ("gopalganj", "Gopalganj"),
            ("jamui", "Jamui"),
            ("jehanabad", "Jehanabad"),
            ("kaimur", "Kaimur"),
            ("katihar", "Katihar"),
            ("khagaria", "Khagaria"),
            ("kishanganj", "Kishanganj"),
            ("lakhisarai", "Lakhisarai"),
            ("madhepura", "Madhepura"),
            ("madhubani", "Madhubani"),
            ("munger", "Munger"),
            ("muzaffarpur", "Muzaffarpur"),
            ("nalanda", "Nalanda"),
            ("nawada", "Nawada"),
            ("patna", "Patna"),
            ("purnia", "Purnia"),
            ("rohtas", "Rohtas"),
            ("saharsa", "Saharsa"),
            ("samastipur", "Samastipur"),
            ("saran", "Saran"),
            ("sheikhpura", "Sheikhpura"),
            ("sheohar", "Sheohar"),
            ("sitamarhi", "Sitamarhi"),
            ("siwan", "Siwan"),
            ("supaul", "Supaul"),
            ("vaishali", "Vaishali"),
            ("west champaran", "West Champaran"),
        ),
    ),
    ("Chandigarh", (("chandigarh", "Chandigarh"),)),
    (
        "Chhattisgarh",
        (
            ("balod", "Balod"),
            ("baloda bazar", "Baloda Bazar"),
            ("balrampur", "Balrampur"),
            ("bastar", "Bastar"),
            ("bemetara", "Bemetara"),
            ("bijapur", "Bijapur"),
            ("bilaspur", "Bilaspur"),
            ("dantewada", "Dantewada"),
            ("dhamtari", "Dhamtari"),
            ("durg", "Durg"),
            ("gariaband", "Gariaband"),
            ("gaurela pendra marwahi", "Gaurela Pendra Marwahi"),
            ("janjgir champa", "Janjgir Champa"),
            ("jashpur", "Jashpur"),
            ("kabirdham", "Kabirdham"),
            ("kanker", "Kanker"),
            ("kondagaon", "Kondagaon"),
            ("korba", "Korba"),
            ("koriya", "Koriya"),
            ("mahasamund", "Mahasamund"),
            ("manendragarh", "Manendragarh"),
            ("mohla manpur", "Mohla Manpur"),
            ("mungeli", "Mungeli"),
            ("narayanpur", "Narayanpur"),
            ("raigarh", "Raigarh"),
            ("raipur", "Raipur"),
            ("rajnandgaon", "Rajnandgaon"),
            ("sakti", "Sakti"),
            ("sarangarh bilaigarh", "Sarangarh Bilaigarh"),
            ("sukma", "Sukma"),
            ("surajpur", "Surajpur"),
            ("surguja", "Surguja"),
        ),
    ),
    (
        "Dadra Nagar Haveli and Daman and Diu",
        (
            ("dadra and nagar haveli", "Dadra and Nagar Haveli"),
            ("daman", "Daman"),
            ("diu", "Diu"),
        ),
    ),
    (
        "Delhi",
        (
            ("central delhi", "Central Delhi"),
            ("east delhi", "East Delhi"),
            ("new delhi", "New Delhi"),
            ("north delhi", "North Delhi"),
            ("north east delhi", "North East Delhi"),
            ("north west delhi", "North West Delhi"),
            ("shahdara", "Shahdara"),
            ("south delhi", "South Delhi"),
            ("south east delhi", "South East Delhi"),
            ("south west delhi", "South West Delhi"),
            ("west delhi", "West Delhi"),
        ),
    ),
    ("Goa", (("north goa", "North Goa"), ("south goa", "South Goa"))),
    (
        "Gujarat",
        (
            ("ahmedabad", "Ahmedabad"),
            ("amreli", "Amreli"),
            ("anand", "Anand"),
            ("aravalli", "Aravalli"),
            ("banaskantha", "Banaskantha"),
            ("bharuch", "Bharuch"),
            ("bhavnagar", "Bhavnagar"),
            ("botad", "Botad"),
            ("chhota udaipur", "Chhota Udaipur"),
            ("dahod", "Dahod"),
            ("dang", "Dang"),
            ("devbhoomi dwarka", "Devbhoomi Dwarka"),
            ("gandhinagar", "Gandhinagar"),
            ("gir somnath", "Gir Somnath"),
            ("jamnagar", "Jamnagar"),
            ("junagadh", "Junagadh"),
            ("kheda", "Kheda"),
            ("kutch", "Kutch"),
            ("mahisagar", "Mahisagar"),
            ("mehsana", "Mehsana"),
            ("morbi", "Morbi"),
            ("narmada", "Narmada"),
            ("navsari", "Navsari"),
            ("panchmahal", "Panchmahal"),
            ("patan", "Patan"),
            ("porbandar", "Porbandar"),
            ("rajkot", "Rajkot"),
            ("sabarkantha", "Sabarkantha"),
            ("surat", "Surat"),
            ("surendranagar", "Surendranagar"),
            ("tapi", "Tapi"),
            ("vadodara", "Vadodara"),
            ("valsad", "Valsad"),
        ),
    ),
    (
        "Haryana",
        (
            ("ambala", "Ambala"),
            ("bhiwani", "Bhiwani"),
            ("charkhi dadri", "Charkhi Dadri"),
            ("faridabad", "Faridabad"),
            ("fatehabad", "Fatehabad"),
            ("gurugram", "Gurugram"),
            ("hisar", "Hisar"),
            ("jhajjar", "Jhajjar"),
            ("jind", "Jind"),
            ("kaithal", "Kaithal"),
            ("karnal", "Karnal"),
            ("kurukshetra", "Kurukshetra"),
            ("mahendragarh", "Mahendragarh"),
            ("mewat", "Mewat"),
            ("palwal", "Palwal"),
            ("panchkula", "Panchkula"),
            ("panipat", "Panipat"),
            ("rewari", "Rewari"),
            ("rohtak", "Rohtak"),
            ("sirsa", "Sirsa"),
            ("sonipat", "Sonipat"),
            ("yamunanagar", "Yamunanagar"),
        ),
    ),
    (
        "Himachal Pradesh",
        (
            ("bilaspur", "Bilaspur"),
            ("chamba", "Chamba"),
            ("hamirpur", "Hamirpur"),
            ("kangra", "Kangra"),
            ("kinnaur", "Kinnaur"),
            ("kullu", "Kullu"),
            ("lahaul spiti", "Lahaul Spiti"),
            ("mandi", "Mandi"),
            ("shimla", "Shimla"),
            ("sirmaur", "Sirmaur"),
            ("solan", "Solan"),
            ("una", "Una"),
        ),
    ),
    (
        "Jammu Kashmir",
        (
            ("anantnag", "Anantnag"),
            ("bandipora", "Bandipora"),
            ("baramulla", "Baramulla"),
            ("budgam", "Budgam"),
            ("doda", "Doda"),
            ("ganderbal", "Ganderbal"),
            ("jammu", "Jammu"),
            ("kathua", "Kathua"),
            ("kishtwar", "Kishtwar"),
            ("kulgam", "Kulgam"),
            ("kupwara", "Kupwara"),
            ("poonch", "Poonch"),
            ("pulwama", "Pulwama"),
            ("rajouri", "Rajouri"),
            ("ramban", "Ramban"),
            ("reasi", "Reasi"),
            ("samba", "Samba"),
            ("shopian", "Shopian"),
            ("srinagar", "Srinagar"),
            ("udhampur", "Udhampur"),
        ),
    ),
    (
        "Jharkhand",
        (
            ("bokaro", "Bokaro"),
            ("chatra", "Chatra"),
            ("deoghar", "Deoghar"),
            ("dhanbad", "Dhanbad"),
            ("dumka", "Dumka"),
            ("east singhbhum", "East Singhbhum"),
            ("garhwa", "Garhwa"),
            ("giridih", "Giridih"),
            ("godda", "Godda"),
            ("gumla", "Gumla"),
            ("hazaribagh", "Hazaribagh"),
            ("jamtara", "Jamtara"),
            ("khunti", "Khunti"),
            ("koderma", "Koderma"),
            ("latehar", "Latehar"),
            ("lohardaga", "Lohardaga"),
            ("pakur", "Pakur"),
            ("palamu", "Palamu"),
            ("ramgarh", "Ramgarh"),
            ("ranchi", "Ranchi"),
            ("sahebganj", "Sahebganj"),
            ("seraikela kharsawan", "Seraikela Kharsawan"),
            ("simdega", "Simdega"),
            ("west singhbhum", "West Singhbhum"),
        ),
    ),
    (
        "Karnataka",
        (
            ("bagalkot", "Bagalkot"),
            ("bangalore rural", "Bangalore Rural"),
            ("bangalore urban", "Bangalore Urban"),
            ("belgaum", "Belgaum"),
            ("bellary", "Bellary"),
            ("bidar", "Bidar"),
            ("chamarajanagar", "Chamarajanagar"),
            ("chikkaballapur", "Chikkaballapur"),
            ("chikkamagaluru", "Chikkamagaluru"),
            ("chitradurga", "Chitradurga"),
            ("dakshina kannada", "Dakshina Kannada"),
            ("davanagere", "Davanagere"),
            ("dharwad", "Dharwad"),
            ("gadag", "Gadag"),
            ("gulbarga", "Gulbarga"),
            ("hassan", "Hassan"),
            ("haveri", "Haveri"),
            ("kodagu", "Kodagu"),
            ("kolar", "Kolar"),
            ("koppal", "Koppal"),
            ("mandya", "Mandya"),
            ("mysore", "Mysore"),
            ("raichur", "Raichur"),
            ("ramanagara", "Ramanagara"),
            ("shimoga", "Shimoga"),
            ("tumkur", "Tumkur"),
            ("udupi", "Udupi"),
            ("uttara kannada", "Uttara Kannada"),
            ("vijayanagara", "Vijayanagara"),
            ("vijayapura", "Vijayapura"),
            ("yadgir", "Yadgir"),
        ),
    ),
    (
        "Kerala",
        (
            ("alappuzha", "Alappuzha"),
            ("ernakulam", "Ernakulam"),
            ("idukki", "Idukki"),
            ("kannur", "Kannur"),
            ("kasaragod", "Kasaragod"),
            ("kollam", "Kollam"),
            ("kottayam", "Kottayam"),
            ("kozhikode", "Kozhikode"),
            ("malappuram", "Malappuram"),
            ("palakkad", "Palakkad"),
            ("pathanamthitta", "Pathanamthitta"),
            ("thiruvananthapuram", "Thiruvananthapuram"),
            ("thrissur", "Thrissur"),
            ("wayanad", "Wayanad"),
        ),
    ),
    ("Ladakh", (("kargil", "Kargil"), ("leh", "Leh"))),
    ("Lakshadweep", (("lakshadweep", "Lakshadweep"),)),
    (
        "Madhya Pradesh",
        (
            ("agar malwa", "Agar Malwa"),
            ("alirajpur", "Alirajpur"),
            ("anuppur", "Anuppur"),
            ("ashoknagar", "Ashoknagar"),
            ("balaghat", "Balaghat"),
            ("barwani", "Barwani"),
            ("betul", "Betul"),
            ("bhind", "Bhind"),
            ("bhopal", "Bhopal"),
            ("burhanpur", "Burhanpur"),
            ("chachaura", "Chachaura"),
            ("chhatarpur", "Chhatarpur"),
            ("chhindwara", "Chhindwara"),
            ("damoh", "Damoh"),
            ("datia", "Datia"),
            ("dewas", "Dewas"),
            ("dhar", "Dhar"),
            ("dindori", "Dindori"),
            ("guna", "Guna"),
            ("gwalior", "Gwalior"),
            ("harda", "Harda"),
            ("hoshangabad", "Hoshangabad"),
            ("indore", "Indore"),
            ("jabalpur", "Jabalpur"),
            ("jhabua", "Jhabua"),
            ("katni", "Katni"),
            ("khandwa", "Khandwa"),
            ("khargone", "Khargone"),
            ("maihar", "Maihar"),
            ("mandla", "Mandla"),
            ("mandsaur", "Mandsaur"),
            ("morena", "Morena"),
            ("nagda", "Nagda"),
            ("narsinghpur", "Narsinghpur"),
            ("neemuch", "Neemuch"),
            ("niwari", "Niwari"),
            ("panna", "Panna"),
            ("raisen", "Raisen"),
            ("rajgarh", "Rajgarh"),
            ("ratlam", "Ratlam"),
            ("rewa", "Rewa"),
            ("sagar", "Sagar"),
            ("satna", "Satna"),
            ("sehore", "Sehore"),
            ("seoni", "Seoni"),
            ("shahdol", "Shahdol"),
            ("shajapur", "Shajapur"),
            ("sheopur", "Sheopur"),
            ("shivpuri", "Shivpuri"),
            ("sidhi", "Sidhi"),
            ("singrauli", "Singrauli"),
            ("tikamgarh", "Tikamgarh"),
            ("ujjain", "Ujjain"),
            ("umaria", "Umaria"),
            ("vidisha", "Vidisha"),
        ),
    ),
    (
        "Maharashtra",
        (
            ("ahmednagar", "Ahmednagar"),
            ("akola", "Akola"),
            ("amravati", "Amravati"),
            ("aurangabad", "Aurangabad"),
            ("beed", "Beed"),
            ("bhandara", "Bhandara"),
            ("buldhana", "Buldhana"),
            ("chandrapur", "Chandrapur"),
            ("dhule", "Dhule"),
            ("gadchiroli", "Gadchiroli"),
            ("gondia", "Gondia"),
            ("hingoli", "Hingoli"),
            ("jalgaon", "Jalgaon"),
            ("jalna", "Jalna"),
            ("kolhapur", "Kolhapur"),
            ("latur", "Latur"),
            ("mumbai city", "Mumbai City"),
            ("mumbai suburban", "Mumbai Suburban"),
            ("nagpur", "Nagpur"),
            ("nanded", "Nanded"),
            ("nandurbar", "Nandurbar"),
            ("nashik", "Nashik"),
            ("osmanabad", "Osmanabad"),
            ("palghar", "Palghar"),
            ("parbhani", "Parbhani"),
            ("pune", "Pune"),
            ("raigad", "Raigad"),
            ("ratnagiri", "Ratnagiri"),
            ("sangli", "Sangli"),
            ("satara", "Satara"),
            ("sindhudurg", "Sindhudurg"),
            ("solapur", "Solapur"),
            ("thane", "Thane"),
            ("wardha", "Wardha"),
            ("washim", "Washim"),
            ("yavatmal", "Yavatmal"),
        ),
    ),
    (
        "Manipur",
        (
            ("bishnupur", "Bishnupur"),
            ("chandel", "Chandel"),
            ("churachandpur", "Churachandpur"),
            ("imphal east", "Imphal East"),
            ("imphal west", "Imphal West"),
            ("jiribam", "Jiribam"),
            ("kakching", "Kakching"),
            ("kamjong", "Kamjong"),
            ("kangpokpi", "Kangpokpi"),
            ("noney", "Noney"),
            ("pherzawl", "Pherzawl"),
            ("senapati", "Senapati"),
            ("tamenglong", "Tamenglong"),
            ("tengnoupal", "Tengnoupal"),
            ("thoubal", "Thoubal"),
            ("ukhrul", "Ukhrul"),
        ),
    ),
    (
        "Meghalaya",
        (
            ("east garo hills", "East Garo Hills"),
            ("east jaintia hills", "East Jaintia Hills"),
            ("east khasi hills", "East Khasi Hills"),
            ("mairang", "Mairang"),
            ("north garo hills", "North Garo Hills"),
            ("ri bhoi", "Ri Bhoi"),
            ("south garo hills", "South Garo Hills"),
            ("south west garo hills", "South West Garo Hills"),
            ("south west khasi hills", "South West Khasi Hills"),
            ("west garo hills", "West Garo Hills"),
            ("west jaintia hills", "West Jaintia Hills"),
            ("west khasi hills", "West Khasi Hills"),
        ),
    ),
    (
        "Mizoram",
        (
            ("aizawl", "Aizawl"),
            ("champhai", "Champhai"),
            ("hnahthial", "Hnahthial"),
            ("khawzawl", "Khawzawl"),
            ("kolasib", "Kolasib"),
            ("lawngtlai", "Lawngtlai"),
            ("lunglei", "Lunglei"),
            ("mamit", "Mamit"),
            ("saiha", "Saiha"),
            ("saitual", "Saitual"),
            ("serchhip", "Serchhip"),
        ),
    ),
    (
        "Nagaland",
        (
            ("chumukedima", "Chumukedima"),
            ("dimapur", "Dimapur"),
            ("kiphire", "Kiphire"),
            ("kohima", "Kohima"),
            ("longleng", "Longleng"),
            ("mokokchung", "Mokokchung"),
            ("mon", "Mon"),
            ("niuland", "Niuland"),
            ("noklak", "Noklak"),
            ("peren", "Peren"),
            ("phek", "Phek"),
            ("tseminyu", "Tseminyu"),
            ("tuensang", "Tuensang"),
            ("wokha", "Wokha"),
            ("zunheboto", "Zunheboto"),
        ),
    ),
    (
        "Odisha",
        (
            ("angul", "Angul"),
            ("balangir", "Balangir"),
            ("balasore", "Balasore"),
            ("bargarh", "Bargarh"),
            ("bhadrak", "Bhadrak"),
            ("boudh", "Boudh"),
            ("cuttack", "Cuttack"),
            ("debagarh", "Debagarh"),
            ("dhenkanal", "Dhenkanal"),
            ("gajapati", "Gajapati"),
            ("ganjam", "Ganjam"),
            ("jagatsinghpur", "Jagatsinghpur"),
            ("jajpur", "Jajpur"),
            ("jharsuguda", "Jharsuguda"),
            ("kalahandi", "Kalahandi"),
            ("kandhamal", "Kandhamal"),
            ("kendrapara", "Kendrapara"),
            ("kendujhar", "Kendujhar"),
            ("khordha", "Khordha"),
            ("koraput", "Koraput"),
            ("malkangiri", "Malkangiri"),
            ("mayurbhanj", "Mayurbhanj"),
            ("nabarangpur", "Nabarangpur"),
            ("nayagarh", "Nayagarh"),
            ("nuapada", "Nuapada"),
            ("puri", "Puri"),
            ("rayagada", "Rayagada"),
            ("sambalpur", "Sambalpur"),
            ("subarnapur", "Subarnapur"),
            ("sundergarh", "Sundergarh"),
        ),
    ),
    (
        "Puducherry",
        (
            ("karaikal", "Karaikal"),
            ("mahe", "Mahe"),
            ("puducherry", "Puducherry"),
            ("yanam", "Yanam"),
        ),
    ),
    (
        "Punjab",
        (
            ("amritsar", "Amritsar"),
            ("barnala", "Barnala"),
            ("bathinda", "Bathinda"),
            ("faridkot", "Faridkot"),
            ("fatehgarh sahib", "Fatehgarh Sahib"),
            ("fazilka", "Fazilka"),
            ("firozpur", "Firozpur"),
            ("gurdaspur", "Gurdaspur"),
            ("hoshiarpur", "Hoshiarpur"),
            ("jalandhar", "Jalandhar"),
            ("kapurthala", "Kapurthala"),
            ("ludhiana", "Ludhiana"),
            ("malerkotla", "Malerkotla"),
            ("mansa", "Mansa"),
            ("moga", "Moga"),
            ("mohali", "Mohali"),
            ("muktsar", "Muktsar"),
            ("pathankot", "Pathankot"),
            ("patiala", "Patiala"),
            ("rupnagar", "Rupnagar"),
            ("sangrur", "Sangrur"),
            ("shaheed bhagat singh nagar", "Shaheed Bhagat Singh Nagar"),
            ("tarn taran", "Tarn Taran"),
        ),
    ),
    (
        "Rajasthan",
        (
            ("ajmer", "Ajmer"),
            ("alwar", "Alwar"),
            ("banswara", "Banswara"),
            ("baran", "Baran"),
            ("barmer", "Barmer"),
            ("bharatpur", "Bharatpur"),
            ("bhilwara", "Bhilwara"),
            ("bikaner", "Bikaner"),
            ("bundi", "Bundi"),
            ("chittorgarh", "Chittorgarh"),
            ("churu", "Churu"),
            ("dausa", "Dausa"),
            ("dholpur", "Dholpur"),
            ("dungarpur", "Dungarpur"),
            ("hanumangarh", "Hanumangarh"),
            ("jaipur", "Jaipur"),
            ("jaisalmer", "Jaisalmer"),
            ("jalore", "Jalore"),
            ("jhalawar", "Jhalawar"),
            ("jhunjhunu", "Jhunjhunu"),
            ("jodhpur", "Jodhpur"),
            ("karauli", "Karauli"),
            ("kota", "Kota"),
            ("nagaur", "Nagaur"),
            ("pali", "Pali"),
            ("pratapgarh", "Pratapgarh"),
            ("rajsamand", "Rajsamand"),
            ("sawai madhopur", "Sawai Madhopur"),
            ("sikar", "Sikar"),
            ("sirohi", "Sirohi"),
            ("sri ganganagar", "Sri Ganganagar"),
            ("tonk", "Tonk"),
            ("udaipur", "Udaipur"),
        ),
    ),
    (
        "Sikkim",
        (
            ("east sikkim", "East Sikkim"),
            ("north sikkim", "North Sikkim"),
            ("pakyong", "Pakyong"),
            ("soreng", "Soreng"),
            ("south sikkim", "South Sikkim"),
            ("west sikkim", "West Sikkim"),
        ),
    ),
    (
        "Tamil Nadu",
        (
            ("ariyalur", "Ariyalur"),
            ("chengalpattu", "Chengalpattu"),
            ("chennai", "Chennai"),
            ("coimbatore", "Coimbatore"),
            ("cuddalore", "Cuddalore"),
            ("dharmapuri", "Dharmapuri"),
            ("dindigul", "Dindigul"),
            ("erode", "Erode"),
            ("kallakurichi", "Kallakurichi"),
            ("kanchipuram", "Kanchipuram"),
            ("kanyakumari", "Kanyakumari"),
            ("karur", "Karur"),
            ("krishnagiri", "Krishnagiri"),
            ("madurai", "Madurai"),
            ("mayiladuthurai", "Mayiladuthurai"),
            ("nagapattinam", "Nagapattinam"),
            ("namakkal", "Namakkal"),
            ("nilgiris", "Nilgiris"),
            ("perambalur", "Perambalur"),
            ("pudukkottai", "Pudukkottai"),
            ("ramanathapuram", "Ramanathapuram"),
            ("ranipet", "Ranipet"),
            ("salem", "Salem"),
            ("sivaganga", "Sivaganga"),
            ("tenkasi", "Tenkasi"),
            ("thanjavur", "Thanjavur"),
            ("theni", "Theni"),
            ("thoothukudi", "Thoothukudi"),
            ("tiruchirappalli", "Tiruchirappalli"),
            ("tirunelveli", "Tirunelveli"),
            ("tirupattur", "Tirupattur"),
            ("tiruppur", "Tiruppur"),
            ("tiruvallur", "Tiruvallur"),
            ("tiruvannamalai", "Tiruvannamalai"),
            ("tiruvarur", "Tiruvarur"),
            ("vellore", "Vellore"),
            ("viluppuram", "Viluppuram"),
            ("virudhunagar", "Virudhunagar"),
        ),
    ),
    (
        "Telangana",
        (
            ("adilabad", "Adilabad"),
            ("bhadradri kothagudem", "Bhadradri Kothagudem"),
            ("hanamkonda", "Hanamkonda"),
            ("hyderabad", "Hyderabad"),
            ("jagtial", "Jagtial"),
            ("jangaon", "Jangaon"),
            ("jayashankar", "Jayashankar"),
            ("jogulamba", "Jogulamba"),
            ("kamareddy", "Kamareddy"),
            ("karimnagar", "Karimnagar"),
            ("khammam", "Khammam"),
            ("komaram bheem", "Komaram Bheem"),
            ("mahabubabad", "Mahabubabad"),
            ("mahbubnagar", "Mahbubnagar"),
            ("mancherial", "Mancherial"),
            ("medak", "Medak"),
            ("medchal", "Medchal"),
            ("mulugu", "Mulugu"),
            ("nagarkurnool", "Nagarkurnool"),
            ("nalgonda", "Nalgonda"),
            ("narayanpet", "Narayanpet"),
            ("nirmal", "Nirmal"),
            ("nizamabad", "Nizamabad"),
            ("peddapalli", "Peddapalli"),
            ("rajanna sircilla", "Rajanna Sircilla"),
            ("ranga reddy", "Ranga Reddy"),
            ("sangareddy", "Sangareddy"),
            ("siddipet", "Siddipet"),
            ("suryapet", "Suryapet"),
            ("vikarabad", "Vikarabad"),
            ("wanaparthy", "Wanaparthy"),
            ("warangal", "Warangal"),
            ("yadadri bhuvanagiri", "Yadadri Bhuvanagiri"),
        ),
    ),
    (
        "Tripura",
        (
            ("dhalai", "Dhalai"),
            ("gomati", "Gomati"),
            ("khowai", "Khowai"),
            ("north tripura", "North Tripura"),
            ("sepahijala", "Sepahijala"),
            ("south tripura", "South Tripura"),
            ("unakoti", "Unakoti"),
            ("west tripura", "West Tripura"),
        ),
    ),
    (
        "Uttar Pradesh",
        (
            ("agra", "Agra"),
            ("aligarh", "Aligarh"),
            ("ambedkar nagar", "Ambedkar Nagar"),
            ("amethi", "Amethi"),
            ("amroha", "Amroha"),
            ("auraiya", "Auraiya"),
            ("ayodhya", "Ayodhya"),
            ("azamgarh", "Azamgarh"),
            ("baghpat", "Baghpat"),
            ("bahraich", "Bahraich"),
            ("ballia", "Ballia"),
            ("balrampur", "Balrampur"),
            ("banda", "Banda"),
            ("barabanki", "Barabanki"),
            ("bareilly", "Bareilly"),
            ("basti", "Basti"),
            ("bhadohi", "Bhadohi"),
            ("bijnor", "Bijnor"),
            ("budaun", "Budaun"),
            ("bulandshahr", "Bulandshahr"),
            ("chandauli", "Chandauli"),
            ("chitrakoot", "Chitrakoot"),
            ("deoria", "Deoria"),
            ("etah", "Etah"),
            ("etawah", "Etawah"),
            ("farrukhabad", "Farrukhabad"),
            ("fatehpur", "Fatehpur"),
            ("firozabad", "Firozabad"),
            ("gautam buddha nagar", "Gautam Buddha Nagar"),
            ("ghaziabad", "Ghaziabad"),
            ("ghazipur", "Ghazipur"),
            ("gonda", "Gonda"),
            ("gorakhpur", "Gorakhpur"),
            ("hamirpur", "Hamirpur"),
            ("hapur", "Hapur"),
            ("hardoi", "Hardoi"),
            ("hathras", "Hathras"),
            ("jalaun", "Jalaun"),
            ("jaunpur", "Jaunpur"),
            ("jhansi", "Jhansi"),
            ("kannauj", "Kannauj"),
            ("kanpur dehat", "Kanpur Dehat"),
            ("kanpur nagar", "Kanpur Nagar"),
            ("kasganj", "Kasganj"),
            ("kaushambi", "Kaushambi"),
            ("kheri", "Kheri"),
            ("kushinagar", "Kushinagar"),
            ("lalitpur", "Lalitpur"),
            ("lucknow", "Lucknow"),
            ("maharajganj", "Maharajganj"),
            ("mahoba", "Mahoba"),
            ("mainpuri", "Mainpuri"),
            ("mathura", "Mathura"),
            ("mau", "Mau"),
            ("meerut", "Meerut"),
            ("mirzapur", "Mirzapur"),
            ("moradabad", "Moradabad"),
            ("muzaffarnagar", "Muzaffarnagar"),
            ("pilibhit", "Pilibhit"),
            ("pratapgarh", "Pratapgarh"),
            ("prayagraj", "Prayagraj"),
            ("raebareli", "Raebareli"),
            ("rampur", "Rampur"),
            ("saharanpur", "Saharanpur"),
            ("sambhal", "Sambhal"),
            ("sant kabir nagar", "Sant Kabir Nagar"),
            ("shahjahanpur", "Shahjahanpur"),
            ("shamli", "Shamli"),
            ("shravasti", "Shravasti"),
            ("siddharthnagar", "Siddharthnagar"),
            ("sitapur", "Sitapur"),
            ("sonbhadra", "Sonbhadra"),
            ("sultanpur", "Sultanpur"),
            ("unnao", "Unnao"),
            ("varanasi", "Varanasi"),
        ),
    ),
    (
        "Uttarakhand",
        (
            ("almora", "Almora"),
            ("bageshwar", "Bageshwar"),
            ("chamoli", "Chamoli"),
            ("champawat", "Champawat"),
            ("dehradun", "Dehradun"),
            ("haridwar", "Haridwar"),
            ("nainital", "Nainital"),
            ("pauri", "Pauri"),
            ("pithoragarh", "Pithoragarh"),
            ("rudraprayag", "Rudraprayag"),
            ("tehri", "Tehri"),
            ("udham singh nagar", "Udham Singh Nagar"),
            ("uttarkashi", "Uttarkashi"),
        ),
    ),
    (
        "West Bengal",
        (
            ("alipurduar", "Alipurduar"),
            ("bankura", "Bankura"),
            ("birbhum", "Birbhum"),
            ("cooch behar", "Cooch Behar"),
            ("dakshin dinajpur", "Dakshin Dinajpur"),
            ("darjeeling", "Darjeeling"),
            ("hooghly", "Hooghly"),
            ("howrah", "Howrah"),
            ("jalpaiguri", "Jalpaiguri"),
            ("jhargram", "Jhargram"),
            ("kalimpong", "Kalimpong"),
            ("kolkata", "Kolkata"),
            ("malda", "Malda"),
            ("murshidabad", "Murshidabad"),
            ("nadia", "Nadia"),
            ("north 24 parganas", "North 24 Parganas"),
            ("paschim bardhaman", "Paschim Bardhaman"),
            ("paschim medinipur", "Paschim Medinipur"),
            ("purba bardhaman", "Purba Bardhaman"),
            ("purba medinipur", "Purba Medinipur"),
            ("purulia", "Purulia"),
            ("south 24 parganas", "South 24 Parganas"),
            ("uttar dinajpur", "Uttar Dinajpur"),
        ),
    ),
]
