# Generated by Django 4.0 on 2023-06-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_newsresponse_news_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsresponse',
            name='news_Response',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
