# Generated by Django 4.0 on 2023-06-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_newsresponse_news_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everything',
            name='news_Response',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
