# Generated by Django 4.0 on 2023-06-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_alter_everything_news_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocnodes',
            name='responseToNews',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='c0',
            name='responseToNews',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t1_l',
            name='responseToNews',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t1_r',
            name='responseToNews',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t2',
            name='responseToNews',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
