# Generated by Django 4.0 on 2023-06-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_alter_adhocnodes_responsetonews_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatmentNodeName', models.CharField(max_length=50, unique=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
