# Generated by Django 4.0 on 2023-06-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_c0_r_c0_l'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='democaticOpinions',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
