# Generated by Django 4.0 on 2023-06-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_alter_t1_l_nodeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t1_l',
            name='child1ID',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='t1_l',
            name='child2ID',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
