# Generated by Django 4.0 on 2023-06-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_alter_t1_l_child1id_alter_t1_l_child2id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t1_l',
            name='nodeID',
            field=models.CharField(default=None, max_length=150, null=True, unique=True),
        ),
    ]
