# Generated by Django 4.0 on 2023-06-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_alter_t1_l_child1id_alter_t1_l_child2id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='democraticopinion2',
            name='sources',
        ),
        migrations.AddField(
            model_name='democraticopinion2',
            name='source_news_channels',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='democraticopinion2',
            name='source_newspapers',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='democraticopinion2',
            name='source_online_news_blogs',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='democraticopinion2',
            name='source_social_media',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
