# Generated by Django 4.0 on 2023-06-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_treatment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
