# Generated by Django 4.0 on 2023-06-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_alter_participant_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='everything',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
