# Generated by Django 4.0 on 2023-06-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0021_everything_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
